\documentclass[a4paper]{article}
\usepackage{Sweave}
\begin{document}

\title{}
\author{}

\maketitle

<<label=libraries, echo=FALSE, eval=TRUE>>=
library(edgeR)

quartz.options(width=5, height=5)
options(editor="/usr/bin/vim")
options(stringsAsFactors=FALSE)

@ 
% Using edgeR, limma, and voom
<<label=linearmodeldesign, echo=FALSE, eval=TRUE>>=
rnadsgn <- model.matrix(~0 + group)
colnames(rnadsgn) <- c('S0c', 'S1c', 'S2c', 'S3c', 'S4c', 'S5c')

contr.matrix <- makeContrasts(S01=S1c - S0c, S12=S2c - S1c, S23=S3c - S2c, S34=S4c - S3c, S45=S5c - S4c,
                              levels=colnames(rnadsgn)) 

@ 
<<label=voomall, echo=FALSE, eval=TRUE>>=
v <- voom(dat.dge, rnadsgn, plot=FALSE) # should be raw counts, see documentation of voom D031417
vfit <- lmFit(v, rnadsgn)
cvfit <- contrasts.fit(vfit, contrasts=contr.matrix)
efit <- eBayes(cvfit)

@ 
% D031417: venn in separate code snippet
<<label=vennplot, echo=FALSE, eval=FALSE>>=
dt <- decideTests(vfit)
vennDiagram(dt)

@ 
% NOTICE: this needs amending, use voom with raw counts!!
<<label=voomprotms, echo=FALSE, eval=FALSE>>=
# only for genes whose proteins are in mss
ismsprot <- nrmcl.dge$genes$Acc %in% rownames(exprs(mss))
#restricting the DGEList object to genes for proteins in mss
xms.dge <- nrmcl.dge[ismsprot,, keep.lib.sizes=FALSE]

pv <- voom(xms.dge, rnadsgn, plot=FALSE)

pvfit <- lmFit(pv, rnadsgn)
cpvfit <- contrasts.fit(pvfit, contrasts=contr.matrix)
pefit <- eBayes(cpvfit)

pdt <- decideTests(pefit)

pdf(paste(UP1PATH, 'Pres/Plots_dima10MAR17/vennGenesInMS.pdf', sep='/'))
vennDiagram(dt, main='Venn Diagram for Genes Transl into MS Prots')
dev.off()

@ 
<<label=heatmapall, echo=FALSE, eval=FALSE>>=
Sweave(paste(USEPROTPATH, 'ds_analysis_A_2FEB17.Rnw', sep='/')) # useLevelplot_v2() and exprs()
restrDge <- function(dgeobj, restrto) {
    ##restrict DGEList object to genes with proteins in mss    
    ismsprot <- dgeobj$genes$Acc %in% restrto
    return(dgeobj[ismsprot,, keep.lib.sizes=FALSE])
}

# only use MS proteins
vfit <- vfit[vfit$genes$Acc %in% rownames(exprs(mss)),]
vf.m <- vfit$coef
vf.df <- as.data.frame(vf.m)

svf.df <- scale(vf.df)
tsvf.df <- t(svf.df)

row.hc <- hclust(stats::dist(tsvf.df))
col.hc <- hclust(stats::dist(svf.df))

dd.col <- as.dendrogram(col.hc)
#pdf(paste(UP1PATH, 'Pres/Plots_dima10MAR17/heatmapGenesInMS.pdf', sep='/'))
useLevelplot_v2(tsvf.df, dd.col)
#dev.off()

@ 
% D031217
<<label=DEanalwithDEseq2, echo=FALSE, eval=FALSE>>=
@ 
% D031017
<<label=barplot, echo=FALSE, eval=FALSE>>=

proteins <- c('D2IYK3', 'J7H3Y9', 'Q9H6I2', 'P52945', 'P78426', 'P01308', 'P01275')
rdf.lst <- genSubsetAbundMat_RNAseq(dimaprots, dat.dge, TRUE)


p <- multiBarPlot_RNAseq(df.lst, rdf.lst)
do.call(grid.arrange, c(p[4:5], ncol=1))





@ 

\end{document}
