\documentclass[a4paper]{article}
\usepackage{Sweave}
\begin{document}

\title{}
\author{}

\maketitle

<<label=libraries, echo=FALSE, eval=TRUE>>=
library(edgeR)

quartz.options(width=5, height=5)
options(editor="/usr/bin/vim")
options(stringsAsFactors=FALSE)

@ 
% Using edgeR, limma, and voom
<<label=linearmodeldesign, echo=FALSE, eval=TRUE>>=
rnadsgn <- model.matrix(~0 + grpgd)
colnames(rnadsgn) <- c('S0c', 'S1c', 'S2c', 'S3c', 'S4c', 'S5c')

contr.matrix <- makeContrasts(S01=S1c - S0c, S12=S2c - S1c, S23=S3c - S2c, S34=S4c - S3c, S45=S5c - S4c,
                              levels=colnames(rnadsgn)) 

@ 
<<label=voomgd, echo=FALSE, eval=TRUE>>=
# limma UsersGuide 15.4: '... the voom transformation is applied to the normalized and filtered DGEList object'
gv <- voom(adat.dge, rnadsgn, plot=FALSE)
gvfit <- lmFit(gv, rnadsgn)
cgvfit <- contrasts.fit(gvfit, contrasts=contr.matrix)
gefit <- eBayes(cgvfit)

@ 
% D031417: venn in separate code snippet
<<label=vennplot, echo=FALSE, eval=FALSE>>=
dt <- decideTests(gefit)
vennDiagram(dt)


@ 
% D031217
<<label=DEanalwithDEseq2, echo=FALSE, eval=FALSE>>=
# TO DO

@ 

% D031017
<<label=barplot, echo=FALSE, eval=FALSE>>=
require(MSnbase)
require(reshape)
require(ggplot2)
require(gridExtra)
#rdf.lst <- genSubsetAbundMat_RNAseq(dimaprots, dat.dge, TRUE)

#proteins <- c('D2IYK3', 'J7H3Y9', 'Q9H6I2', 'O43174', 'Q08426')
#proteins <- c('O14529', 'P09668', 'P36871', 'P52945', 'P78426', 'P01308', 'P01275') # CUX2, CTSH, PGM1
#proteins <- c('O14529', 'P09668', 'P36871', 'Q5EE01', 'Q5VYX0', 'Q12840', 'P07911', 'P80370', 'P51684') # CUX2, CTSH, PGM1, CENPW, c10orf59, KIF5A, Uromodulin, DLK1
#proteins <- c('Q5EE01', 'Q5VYX0', 'Q12840', 'P07911', 'P80370', 'P51684', 'P08908')

proteins <- c('A8K9T3', 'P61764', 'Q59FR8', 'A0A024RB36')

rdf.lst <- genSubsetAbundMat_RNAseq(proteins, dat.dge, TRUE)

# from MeltonProteomics/ds_analysis_A_2FEB17.Rnw::label=multiplotsprotlistsD2717
acclst <- list(s227=r227.df$Accession, s238=r238.df$Accession, s239=r239.df$Accession, s243=r243.df$Accession)
xl <-  makeSubsetExprMatrix(1, adat.lst) # adat.lst in resources:label=msnsetfromsubsets
msl <- makeMSnSetfromSampleSubsets(xl, p.df) # p.df in resources:label=MSnSetcombined
z <- presentNSamples(proteins, acclst) # see MeltonProteomics:ds_analysis_A_2FEB17.Rnw
df.lst <- genSubsetAbundMat(z, msl, TRUE)

p <- multiBarPlot_RNAseq(df.lst, rdf.lst)
do.call(grid.arrange, c(p[4:5], ncol=1))

@ 

\end{document}
